language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run flow
  - npm test
  - npm run build
deploy:
  provider: surge
  project: ./build
  domain: www.talktovarun.com
  skip_cleanup: true
